[package]
name = "zenith-float-macro"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "expr! procedural macro for zenith-float."
readme = "README.md"
keywords = ["arbitrary-precision", "macro", "numeric"]
categories = ["mathematics"]

[lib]
proc-macro = true

[dependencies]
quote = { version = "1", default-features = false }
syn = { version = "1", default-features = false, features = ["parsing", "proc-macro", "full", "extra-traits", "printing"] }
zenith-float-num = { version = "1.0.2", path = "../zenith-float-num", default-features = false }
proc-macro2 = { version = "1", default-features = false }
